name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authorize
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 13.2.1
      - run: xcodebuild -version
      - name: Release
        run: sh .scripts/package.sh
