name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authorize
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Release
        run: sh .scripts/package.sh
